# Generated by Django 4.2 on 2023-05-02 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+201234567890' or '01234567890'", regex='^(?:\\+20|0)?1\\d{9}$')]),
        ),
    ]
