# Generated by Django 4.2 on 2023-05-17 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contactus_remove_customuser_address_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default=None, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+201234567890' or '01234567890'", regex='^(?:\\+20|0)?1\\d{9}$')]),
            preserve_default=False,
        ),
    ]
