# Generated by Django 4.2 on 2023-05-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymenthistory'),
        ('orders', '0009_remove_order_total_price'),
    ]

    operations = [
    ]
