# Generated by Django 4.2 on 2023-05-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20230509_2228'),
        ('orders', '0010_merge_20230510_0259'),
    ]

    operations = [
    ]
