# Generated by Django 4.2 on 2023-05-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20230510_2208'),
        ('orders', '0011_merge_20230511_0258'),
    ]

    operations = [
    ]
