# Generated by Django 4.2 on 2023-05-10 22:10

import cloudinary.models
from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, validators=[products.models.validate_image_size, products.models.validate_image_extension], verbose_name='images'),
            preserve_default=False,
        ),
    ]
