# Generated by Django 4.2 on 2023-05-10 22:22

import cloudinary.models
from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, null=True, validators=[products.models.validate_image_size, products.models.validate_image_extension], verbose_name='images'),
        ),
    ]
