# Generated by Django 4.2 on 2023-05-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_image'),
        ('products', '0008_category_description_category_image'),
    ]

    operations = [
    ]
